export const Themes: string[] = [
  'light',
  'dark',
  // 'cupcake',
  // 'bumblebee',
  // 'emerald',
  // 'corporate',
  // "retro",
  // "cyberpunk",
  // 'cmyk',
  // "valentine",
  // 'garden',
  // "lofi",
  // "pastel",
  // 'fantasy',
  // "wireframe",
  // 'autumn',
  // 'acid',
  // "lemonade",
  // "winter",
  // 'nord',
  // 'synthwave',
  // 'halloween',
  // 'forest',
  // "aqua",
  // 'black',
  // "luxury",
  // 'dracula',
  // 'business',
  // 'night',
  // "coffee",
  // 'dim',
  // 'sunset',
];
